steps:

  #Decrypt key
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['kms', 'decrypt', '--ciphertext-file=ci/secrets/pypi-secrets.sh.enc',
           '--plaintext-file=ci/secrets/pypi-secrets.sh', '--location=global',
           '--keyring=myelin-keyring', '--key=myelin-key']
    id: 'secret'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['kms', 'decrypt', '--ciphertext-file=ci/secrets/dockerhub-secrets.sh.enc',
           '--plaintext-file=ci/secrets/dockerhub-secrets.sh', '--location=global',
           '--keyring=myelin-keyring', '--key=myelin-key']
    id: 'docker-secrets'

  - name: 'python:2.7-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        python2 setup.py bdist_wheel

  - name: 'python:3.6-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        python3 setup.py bdist_wheel
        pip3 install twine
        source ci/secrets/pypi-secrets.sh
        twine upload --username $$USERNAME --password $$PASSWORD  --repository-url https://upload.pypi.org/legacy/ dist/*
    id: 'twine-upload'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        source ci/secrets/dockerhub-secrets.sh
        docker login --username=$$DOCKERHUB_USERID --password=$$DOCKERHUB_PASSWORD
        docker build -t myelinio/ludwig:0.2.1 ci/docker -f ci/docker/Dockerfile
        docker push myelinio/ludwig:0.2.1
        docker build -t myelinio/ludwig-deploy:0.2.1 ci/docker -f ci/docker/Dockerfile-deploy
        docker push myelinio/ludwig-deploy:0.2.1

    waitFor: ['docker-secrets', 'twine-upload']
    id: 'docker'

timeout: 3600s
