steps:

  #Decrypt key
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['kms', 'decrypt', '--ciphertext-file=ci/secrets/pypi-secrets.sh.enc',
           '--plaintext-file=ci/secrets/pypi-secrets.sh', '--location=global',
           '--keyring=myelin-keyring', '--key=myelin-key']
    id: 'secret'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['kms', 'decrypt', '--ciphertext-file=ci/secrets/dockerhub-secrets.sh.enc',
           '--plaintext-file=ci/secrets/dockerhub-secrets.sh', '--location=global',
           '--keyring=myelin-keyring', '--key=myelin-key']
    id: 'docker-secrets'

  - name: 'python:2.7-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        python2 setup.py bdist_wheel

  - name: 'python:3.6-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        python3 setup.py bdist_wheel
        pip3 install twine
        source ci/secrets/pypi-secrets.sh
        twine upload --username $$USERNAME --password $$PASSWORD  --repository-url https://upload.pypi.org/legacy/ dist/*
    id: 'twine-upload'

  - name: 'python:3.6-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        until pip download --no-dependencies ludwig-myelin==$_LUDWIG_VERSION
        do
          pip download --no-dependencies ludwig-myelin==$_LUDWIG_VERSION
          sleep 5
        done
    id: 'twine-wait'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        source ci/secrets/dockerhub-secrets.sh
        docker login --username=$$DOCKERHUB_USERID --password=$$DOCKERHUB_PASSWORD
        docker build -t myelinio/ludwig:$_LUDWIG_VERSION ci/docker -f ci/docker/Dockerfile --build-arg ludwig_version=$_LUDWIG_VERSION
        docker push myelinio/ludwig:$_LUDWIG_VERSION

    waitFor: ['docker-secrets', 'twine-wait']
    id: 'docker-ludwig'
    
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        source ci/secrets/dockerhub-secrets.sh
        docker login --username=$$DOCKERHUB_USERID --password=$$DOCKERHUB_PASSWORD
        docker build -t myelinio/ludwig-deploy:$_LUDWIG_VERSION ci/docker -f ci/docker/Dockerfile-deploy --build-arg ludwig_version=$_LUDWIG_VERSION
        docker push myelinio/ludwig-deploy:$_LUDWIG_VERSION

    waitFor: ['docker-secrets', 'twine-wait']
    id: 'docker-ludwig-deploy'    
    
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        source ci/secrets/dockerhub-secrets.sh
        docker login --username=$$DOCKERHUB_USERID --password=$$DOCKERHUB_PASSWORD
        docker build -t myelinio/ludwig-horovod-gpu:$_LUDWIG_VERSION ci/docker -f ci/docker/Dockerfile-horovod-gpu --build-arg ludwig_version=$_LUDWIG_VERSION
        docker push myelinio/ludwig-horovod-gpu:$_LUDWIG_VERSION

    waitFor: ['docker-secrets', 'twine-wait']
    id: 'docker-ludwig-horovod-gpu'    
    
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        source ci/secrets/dockerhub-secrets.sh
        docker login --username=$$DOCKERHUB_USERID --password=$$DOCKERHUB_PASSWORD
        docker build -t myelinio/ludwig-horovod-cpu:$_LUDWIG_VERSION ci/docker -f ci/docker/Dockerfile-horovod-cpu --build-arg ludwig_version=$_LUDWIG_VERSION
        docker push myelinio/ludwig-horovod-cpu:$_LUDWIG_VERSION

    waitFor: ['docker-secrets', 'twine-wait']
    id: 'docker-ludwig-horovod-cpu'
    
substitutions:
  _LUDWIG_VERSION: 0.2.1.32

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 3600s
