ARG ludwig_version

FROM python:3.6-slim

COPY ./requirements.txt requirements.txt

COPY ./pip-wait.sh pip-wait.sh
ENV _LUDWIG_VERSION=$ludwig_version
RUN pip-wait.sh

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc build-essential \
    && rm -rf /var/lib/apt/lists/* \
    && pip install -r  requirements.txt \
    && apt-get purge -y --auto-remove gcc build-essential

ENV MODEL_PATH /tmp
ENV PORT 5000


CMD ludwig serve  --model_path ${MODEL_PATH}/experiment_run/model/ --port ${PORT}