FROM python:3.6-slim

COPY ./requirements.txt requirements.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc build-essential \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get purge -y --auto-remove gcc build-essential

RUN pip install -r  requirements.txt

ENV MODEL_PATH /tmp
ENV PORT 5000


CMD ludwig serve  --model_path ${MODEL_PATH}/experiment_run/model/ --port ${PORT}